### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by shenyx110** [AnonymousHacker1279/IWCompatibilityBridge#19]
[crash-2024-10-10_20.44.04-server.txt](https://github.com/user-attachments/files/17328331/crash-2024-10-10_20.44.04-server.txt)

I hope this message finds you well. I am writing to report an issue that I encountered while using the iwcompatbridge mod in conjunction with the Accessories mod on my Minecraft server.

Details of the Issue:
Error Type: java.lang.StackOverflowError
Main Mods Involved:
Accessories
iwcompatbridge
Possible Source of the Problem:
The issue seems to be caused by internal logic within the CurioInventory.init method or interactions between Accessories and iwcompatbridge, leading to a recursive call.
Additional Information:
The error occurs during the initialization of the CurioInventory in the Accessories mod.
The problem might be related to a circular reference or infinite recursion involving the DynamicStackHandler.isItemValid method.
I have attached the full crash log for your reference. Please let me know if you need any additional information or if there are any known compatibility issues or updates that could address this problem.

Thank you for your attention to this matter. I appreciate any assistance you can provide in resolving this issue.

Please note that my English is not very good, and this report was generated with the help of an AI. I will do my best to provide all the necessary information.

**Comment by AnonymousHacker1279** [comment]
Hello!

I was actually originally using Curios API Continuation as the Curios port but found that to be an issue during my testing. The issue is a stack overflow within the `CuriosApi#getCuriosInventory()` method on world load. Unfortunately, it is not something I can seem to work around, so I suggest opening an issue report on their repository and linking this issue. The event handler where the crash occurs in IWCB can be found [here](https://github.com/AnonymousHacker1279/IWCompatibilityBridge/blob/1af5b75da6d635f8499ef2456077f7a8b4ef9a64/src/main/java/tech/anonymoushacker1279/iwcompatbridge/plugin/curios/CuriosEventHandler.java).

It is important to note that this crash does not occur with Adorned, the recommended Curios fork I mark as compatible with IWCB. Both Adorned and Curios API Continuation claim to expose the same API surface as Curios, so theoretically both should work. If possible, I suggest swapping it for Adorned in your modpack and seeing if the crash still occurs.

**Comment by shenyx110** [comment]
Sorry I got the module wrong, it's not Accessories, it's Curios API Continuation, but I've also reported the problem to the developers of Curios API Continuation https://github.com/SSKirillSS/Curios/issues/18 and the Adorned you said seems to have a bug in the command that doesn't work properly curios add/set can't work

**Comment by AnonymousHacker1279** [comment]
I see. I will monitor the other issue and see if their dev has any suggestions or insight into the issue. I have not personally used the commands in Adorned so I was unaware they were broken.

I'll keep this issue open for the time being.

**Comment by AnonymousHacker1279** [comment]
With the release of Curios API Continuation 9.0.14, this issue seems to be resolved and I can no longer reproduce it in my environment.
